name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          DISABLE_ESLINT_PLUGIN=true npm run build

      - name: Install Capacitor iOS
        run: npx cap sync ios

      - name: Clean Xcode Build
        run: |
          xcodebuild clean -workspace ios/App/App.xcworkspace -scheme App -configuration Release

      - name: Build iOS App Archive
        run: |
          xcodebuild archive \
          -workspace ios/App/App.xcworkspace \
          -scheme App \
          -configuration Release \
          -archivePath ./build/App.xcarchive \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGN_IDENTITY="" \
          PROVISIONING_PROFILE_SPECIFIER="Automatic" \
          DEVELOPMENT_TEAM="YOUR_TEAM_ID"  # Replace with actual team ID
        continue-on-error: false  # Stop if the archive fails

      - name: Check Archive Existence
        run: |
          if [ ! -d "./build/App.xcarchive" ]; then
            echo "Archive not created!";
            exit 1;
          fi

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
          -archivePath ./build/App.xcarchive \
          -exportPath ./build \
          -exportOptionsPlist ios/App/exportOptions.plist \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGN_IDENTITY=""
        continue-on-error: false  # Stop if the export fails

      - name: Check if IPA Exists
        run: |
          if [ ! -f "./build/App.ipa" ]; then
            echo "IPA file not found!";
            exit 1;
          fi

      - name: Upload IPA to Appetize.io
        run: |
          curl https://api.appetize.io/v1/apps \
          -F "file=@./build/App.ipa" \
          -F "platform=ios" \
          -F "token=$APPETIZE_API_TOKEN" \
          -F "note=BlackApp iOS Build"
