name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          DISABLE_ESLINT_PLUGIN=true npm run build

      - name: Install Capacitor iOS
        run: npx cap sync ios

      - name: Archive the iOS app (without signing)
        run: |
          xcodebuild archive \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath ./build/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            DEVELOPMENT_TEAM=""

      - name: Create exportOptions.plist
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > ios/App/exportOptions.plist
          echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> ios/App/exportOptions.plist
          echo '<plist version="1.0">' >> ios/App/exportOptions.plist
          echo '<dict>' >> ios/App/exportOptions.plist
          echo '  <key>method</key>' >> ios/App/exportOptions.plist
          echo '  <string>ad-hoc</string>' >> ios/App/exportOptions.plist
          echo '  <key>signingStyle</key>' >> ios/App/exportOptions.plist
          echo '  <string>manual</string>' >> ios/App/exportOptions.plist
          echo '  <key>signingCertificate</key>' >> ios/App/exportOptions.plist
          echo '  <string></string>' >> ios/App/exportOptions.plist
          echo '  <key>teamID</key>' >> ios/App/exportOptions.plist
          echo '  <string></string>' >> ios/App/exportOptions.plist
          echo '</dict>' >> ios/App/exportOptions.plist
          echo '</plist>' >> ios/App/exportOptions.plist

      - name: Export the IPA (unsigned)
        run: |
          xcodebuild -exportArchive \
            -archivePath ./build/App.xcarchive \
            -exportPath ./build \
            -exportOptionsPlist ios/App/exportOptions.plist

      - name: Upload IPA to Appetize.io
        run: |
          curl https://api.appetize.io/v1/apps \
          -F "file=@./build/App.ipa" \
          -F "platform=ios" \
          -F "token=$APPETIZE_API_TOKEN" \
          -F "note=BlackApp iOS Build"
