name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Set up Capacitor iOS platform
      run: npx cap add ios

    - name: Install CocoaPods
      run: |
        cd ios/App
        pod install

    - name: Build iOS app
      run: |
        xcodebuild -workspace ios/App/App.xcworkspace \
                   -scheme App \
                   -sdk iphoneos \
                   -configuration Release \
                   -archivePath ${{ github.workspace }}/App.xcarchive \
                   archive

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
                   -archivePath ${{ github.workspace }}/App.xcarchive \
                   -exportOptionsPlist ios/App/exportOptions.plist \
                   -exportPath ${{ github.workspace }}/build

    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: WakandaApp-IPA
        path: build/App.ipa
