name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Install Capacitor iOS
        run: npx cap sync ios

      - name: Build iOS App
        run: xcodebuild archive -workspace ios/App/App.xcworkspace -scheme App -configuration Release -archivePath ./build/App.xcarchive

      - name: Export IPA
        run: xcodebuild -exportArchive -archivePath ./build/App.xcarchive -exportPath ./build -exportOptionsPlist ios/App/exportOptions.plist
        env:
          DEVELOPMENT_TEAM: ""
          CODE_SIGN_IDENTITY: ""
          PROVISIONING_PROFILE: ""

      - name: Upload IPA to Appetize.io
        run: |
          curl https://api.appetize.io/v1/apps \
          -F "file=@./build/App.ipa" \
          -F "platform=ios" \
          -F "token=$APPETIZE_API_TOKEN" \
          -F "note=BlackApp iOS build"

